# Generated by Django 4.2.7 on 2023-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaFILENAME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prosmotr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
