# Generated by Django 4.2.7 on 2023-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaFILENAME', '0002_prosmotr_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smotret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
